#!/bin/sh

# Fail fast
set -e

shutdown() {
    echo "Shutting down..."

    sync
    umount -a -r

    poweroff -f
}

do_reboot() {
    echo "Rebooting..."
    sync
    umount -a -r
    /sbin/reboot -f
}

cat <<'EOF'
 ███▄ ▄███▓ ██▓ ██▀███   ▄▄▄       ██▓
▓██▒▀█▀ ██▒▓██▒▓██ ▒ ██▒▒████▄    ▓██▒
▓██    ▓██░▒██▒▓██ ░▄█ ▒▒██  ▀█▄  ▒██▒
▒██    ▒██ ░██░▒██▀▀█▄  ░██▄▄▄▄██ ░██░
▒██▒   ░██▒░██░░██▓ ▒██▒ ▓█   ▓██▒░██░
░ ▒░   ░  ░░▓  ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░░▓  
░  ░      ░ ▒ ░  ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░
░      ░    ▒ ░  ░░   ░   ░   ▒    ▒ ░
       ░    ░     ░           ░  ░ ░  
EOF

echo "[minit] Starting minimal init..."

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev || mount -t tmpfs tmpfs /dev
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /run
echo "[minit] Mounted filesystems"

trap shutdown INT TERM
trap do_reboot HUP
echo "[minit] Trapped signals"

reap() {
    while true; do
        wait
    done
}
reap &
REAPER_PID=$!

echo "[minit] Starting login on tty1"
/bin/busybox getty -L tty1 0 linux &
/bin/busybox getty -L tty2 0 linux &
/bin/busybox getty -L tty3 0 linux &
/bin/busybox getty -L tty4 0 linux &